### ISSUE TITLE
history.goBack and hash-based routing

### ISSUE THREAD

**Issue by wparrott-touchnet** [ReactTraining/history#625] opened 2018-10-01 15:36 UTC
Our single-page app is using the react-router hash history, and some of the views in the application have a "Go Back" link. This behaves as expected in Chrome, but the other three browsers we support (Firefox, Edge, and IE11) all break. I have a minimal demo pushed to a [repository here](https://github.com/chimericdream/history-bug-poc). Copied below is what I put in the readme.

---

#### To reproduce the bug

1. download or clone the repository
1. run `npm install`
1. run `npm start`
1. navigate to `http://localhost:3000/`
1. navigate between the pages by clicking the links

#### Expected behavior

Clicking "Go Back" should always take you to the previous page within the app

#### Actual behavior

Works as expected on Chrome, but not in Firefox, Internet Explorer, and Edge. In those three, clicking "Go Back" always takes you to the first page in the application.

---

I'm not sure if this is a bug here, in react-router, or if we're misusing something, but it seems like a simple/logical enough use case that I _hope_ the latter isn't the case.

**Comment by gagandeepp** [comment] 2018-12-13 09:18
@wparrott-touchnet  Please close this one as well

**Comment by wparrott-touchnet** [comment] 2018-12-13 14:00
The bug is still present, even in the latest beta versions of `react-router` and `history`. Aside from lack of replies, I am not sure why the other issue was closed. It isn't resolved, as indicated by the bot that closed the issue.

I'd be happy to close one of the two issues if you know which module is the one with the bug, but I don't think the issues should be closed without a fix, or at least an explanation of what may be incorrect in my example.

**Comment by RXminuS** [comment] 2019-01-21 17:33
I have the same issue, @gagandeepp why are you closing them?

**Comment by mjackson** [comment] 2019-03-26 23:49
This is a problem with your `<Link>`, not hash history.

The problem is that your `<Link>` is taking the user back to `/`, which is then redirecting to `/page1`. If you want to prevent the link from navigating and instead navigate manually using `history.goBack`, you need to first `preventDefault` on the `click` event, like this:

![Screen Shot 2019-03-26 at 4 43 27 PM](https://user-images.githubusercontent.com/92839/55040697-ba689800-4fe6-11e9-833b-483d5fb89ed8.png)

Then everything works as you'd expect (this is Firefox):

![not-a-bug](https://user-images.githubusercontent.com/92839/55040751-0ca9b900-4fe7-11e9-8da9-084dcb66344b.gif)

**Closed by mjackson** 2019-03-26 23:49 UTC

**Comment by wparrott-touchnet** [comment] 2019-03-29 12:56
I _knew_ it was something obvious I was missing. Thanks!

![mundane-detail](https://user-images.githubusercontent.com/38440975/55234010-2110d000-51f8-11e9-87a5-6dd42eeb72af.jpg)
