### ISSUE TITLE
history.listen not triggered on hash changes

### ISSUE THREAD

**Issue by vpezeshkian** [ReactTraining/history#384] opened 2016-11-02 20:23 UTC
Hi. I upgraded react-router library to version `3.0.0` which uses `History v3.0.0`, but this caused `history.listen` not triggering on hash changes. 

Inspired by [this answer](https://stackoverflow.com/questions/16267339/s3-static-website-hosting-route-all-paths-to-index-html/34958026#34958026) on stackoverflow, I'm listening to URL changes and do stuff to history. This works perfectly with react-router version `2.8.1` which uses `History v2.1.2`. 

Could you please tell me what changes do I have to make to have the same result.

**Comment by KrofDrakula** [comment] 2016-11-17 15:28
Same here; using `createHashHistory()` and changing the URL in the address bar (the hash part) doesn't cause listeners to be triggered, even though the `hashchange` event fires on `window`.

**Comment by DimitryDushkin** [comment] 2017-01-28 19:30
Same here

**Comment by timdorr** [comment] 2017-02-08 19:21
Can you post some example code where this isn't working? Ironically, we're seeing the opposite effect (double listener calls) on React Router.

**Comment by DimitryDushkin** [comment] 2017-02-08 19:40
@timdorr I've resolved my issue — https://github.com/ReactTraining/react-router/issues/4370#issuecomment-275873789 — and it was not history problem.

**Comment by timdorr** [comment] 2017-02-08 19:44
@vpezeshkian Can you provide some code? It looks like you have some other people with the same problem, based on the reactions to your comment. If anyone has any examples of using the library that reproduce this problem, that would be super-helpful.

**Comment by aij** [comment] 2017-02-22 18:42
I'm seeing this too, though with v2.x.

We're using redux-router and scroll-behavior, and I was trying to fix scroll-behavior to do the right thing when clicking #links and going back.

I'm seeing `transitionTo` in `createHistory.js` gets called with `nextLocation.key === location.key` even though `nextLocation.hash != location.hash`, so `locationsAreEqual` returns true and the update is squelched. 

It only seems to happen after following internal links and then using the back button, possibly requiring additional following of internal links though I'm not sure I can reproduce it 100% reliably yet...

Sorry I don't have a small code sample yet, but I can run

    u = $r.props.history.listen(e => console.log('history event:', o))

in the console and it will miss updates that

    window.addEventListener('popstate', console.log, false)

does get. This is with Chrome  57 beta BTW.

I'll see if I can get a small repro example.

**Comment by aij** [comment] 2017-02-22 19:02
Actually, here's a fairly small example.

1. Open below file and open the JS console to see log messages.
1. Click `t1`
1. Click `t2`
1. Click back button.
1. Click `t3`.

Note that the last step was the only one not logged.

    <script src="https://unpkg.com/history@2.1.2/umd/history.js"></script>
    <script>
      h = History.createHistory()
      unlist = h.listen(console.log)
    </script>
    <ul>
      <li><a href="#t1">t1</a>
      <li><a href="#t2">t2</a>
      <li><a href="#t3">t3</a>
      <li><a href="#t4">t4</a>
    </ul>
    
    <p id="t1" style="height: 100%"> T1
    <p id="t2" style="height: 100%"> T2
    <p id="t3" style="height: 100%"> T3
    <p id="t4" style="height: 100%"> T4

**Comment by vpezeshkian** [comment] 2017-02-22 19:17
Sorry for late response,
My own example is this:

```javascript
import { Router, Route, useRouterHistory, IndexRoute } from 'react-router'
import { createHistory } from 'history'
const history = useRouterHistory(createHistory)();
  history.listen(location => {
    const path = (/#(\/.*)$/.exec(location.hash) || [])[1];
    if(path) history.replace(path);
  });

<Router history={history}>...rest of the routs here...</Router>
```
My experience is not like @DimitryDushkin where clicking causes this, I just can't load the page, it just goes to `/`. meaning if hit `localhost:3000/account/123` it serves `localhost:3000`, since it doesn't put the `#` and replace, because it did not register the listener. 

This is happening with v3.x of react-router and above.

**Comment by timdorr** [comment] 2017-02-22 19:31
@vpezeshkian The default `createHistory` is a browser history. It doesn't listen to hash changes. If you need that, you have to add a listener for the `hashchange` event to handle it. Also, under 3.0, the initial `listen` callback doesn't immediately fire, so I wouldn't expect that listener to ever actually run.

@aij That isn't the version of history we're dealing with here. 

Looks like this is an error outside the library, so I'm closing this out.

**Closed by timdorr** 2017-02-22 19:31 UTC
Labels: v3

**Comment by aij** [comment] 2017-02-22 20:55
@timdorr You're right. My above example seems to work fine with 4.5.1 as well as 3.2.1. I'll see if I can upgrade redux-router to use a newer version of history instead. Do you care for a bug report against v2 or is it pretty much abandoned at this point?

**Comment by timdorr** [comment] 2017-02-22 21:12
Nothing's happening with it. We're recommend router 3.0 at this time, with 4.0 coming very soon. All 2.x stuff isn't maintained anymore.
